import type {
  ActivityMetrics,
  AdminActivity,
  AdminActivityDetail,
  Achievement,
  AdminUser,
  CommunityPost,
  CommunityPostDetail,
  EcoCategory,
  Habit,
} from "@/lib/types";

export const mockUsers: AdminUser[] = [
  {
    id: "user-1",
    username: "akmaral",
    email: "akmaral@ecoiz.app",
    role: "ADMIN",
    isEmailVerified: true,
    ecoPoints: 2480,
    streakDays: 18,
    postsCount: 12,
    createdAt: "2025-02-10",
    status: "ACTIVE",
  },
  {
    id: "user-2",
    username: "nurdana",
    email: "nurdana@ecoiz.app",
    role: "MODERATOR",
    isEmailVerified: true,
    ecoPoints: 1640,
    streakDays: 9,
    postsCount: 7,
    createdAt: "2025-02-19",
    status: "ACTIVE",
  },
  {
    id: "user-3",
    username: "green_step",
    email: "user1@ecoiz.app",
    role: "USER",
    isEmailVerified: false,
    ecoPoints: 820,
    streakDays: 4,
    postsCount: 3,
    createdAt: "2025-03-01",
    status: "REVIEW",
  },
  {
    id: "user-4",
    username: "urban_leaf",
    email: "user2@ecoiz.app",
    role: "USER",
    isEmailVerified: true,
    ecoPoints: 320,
    streakDays: 1,
    postsCount: 1,
    createdAt: "2025-03-12",
    status: "SUSPENDED",
  },
];

export const mockActivities: AdminActivityDetail[] = [
  {
    id: "activity-1",
    userId: "user-1",
    username: "akmaral",
    userEmail: "akmaral@ecoiz.app",
    category: "Транспорт",
    title: "Пешая прогулка",
    co2Saved: 1.5,
    points: 20,
    note: "Университет вместо такси",
    media: [],
    createdAt: "2026-03-29T08:30:00Z",
  },
  {
    id: "activity-2",
    userId: "user-2",
    username: "nurdana",
    userEmail: "nurdana@ecoiz.app",
    category: "Вода",
    title: "Короткий душ",
    co2Saved: 0,
    points: 15,
    note: "Сократила душ до 5 минут",
    media: [],
    createdAt: "2026-03-29T09:10:00Z",
  },
  {
    id: "activity-3",
    userId: "user-3",
    username: "green_step",
    userEmail: "user1@ecoiz.app",
    category: "Отходы",
    title: "Сортировка бумаги",
    co2Saved: 0,
    points: 10,
    note: "Раздельный сбор дома",
    media: [],
    createdAt: "2026-03-28T14:00:00Z",
  },
];

export const mockActivityMetrics: ActivityMetrics = {
  totalActivities: mockActivities.length,
  totalPoints: mockActivities.reduce((sum, item) => sum + item.points, 0),
  totalCo2Saved: Number(
    mockActivities.reduce((sum, item) => sum + item.co2Saved, 0).toFixed(1),
  ),
  uniqueUsers: new Set(mockActivities.map((item) => item.userId)).size,
};

export const mockCategories: EcoCategory[] = [
  {
    id: "cat-1",
    name: "transport",
    description: "Sustainable transport",
    color: "orange",
    icon: "transport",
  },
  {
    id: "cat-2",
    name: "water",
    description: "Water conservation",
    color: "blue",
    icon: "water",
  },
  {
    id: "cat-3",
    name: "plastic",
    description: "Plastic reduction",
    color: "teal",
    icon: "plastic",
  },
];

export const mockHabits: Habit[] = [
  {
    id: "habit-1",
    title: "Пешая прогулка",
    category: "transport",
    points: 20,
    co2Value: 1.5,
    waterValue: 0,
    energyValue: 0,
  },
  {
    id: "habit-2",
    title: "Короткий душ",
    category: "water",
    points: 15,
    co2Value: 0,
    waterValue: 25,
    energyValue: 0,
  },
  {
    id: "habit-3",
    title: "Сортировка",
    category: "waste",
    points: 15,
    co2Value: 0,
    waterValue: 0,
    energyValue: 0,
  },
  {
    id: "habit-4",
    title: "Выключил свет",
    category: "electricity",
    points: 10,
    co2Value: 0,
    waterValue: 0,
    energyValue: 2,
  },
];

export const mockAchievements: Achievement[] = [
  {
    id: "achievement-1",
    title: "Эко-новичок",
    description: "Использовать многоразовую бутылку 10 раз",
    icon: "badge_1",
    targetValue: 10,
    rewardPoints: 50,
  },
  {
    id: "achievement-2",
    title: "Неделя силы",
    description: "7 раз пройти пешком вместо такси",
    icon: "badge_2",
    targetValue: 7,
    rewardPoints: 70,
  },
  {
    id: "achievement-3",
    title: "Экономист",
    description: "30 дней подряд отмечать экономию электроэнергии",
    icon: "badge_3",
    targetValue: 30,
    rewardPoints: 150,
  },
  {
    id: "achievement-4",
    title: "Мастер сортировки",
    description: "Отсортировать мусор 40 раз",
    icon: "badge_4",
    targetValue: 40,
    rewardPoints: 120,
  },
  {
    id: "achievement-5",
    title: "Зеленый наставник",
    description: "50 дней сокращать время душа на 2-3 минуты",
    icon: "badge_5",
    targetValue: 50,
    rewardPoints: 200,
  },
  {
    id: "achievement-6",
    title: "Друг природы",
    description: "Подписаться на 10 пользователей",
    icon: "badge_follow",
    targetValue: 10,
    rewardPoints: 60,
  },
  {
    id: "achievement-7",
    title: "Вдохновитель",
    description: "Опубликовать 5 постов",
    icon: "badge_post",
    targetValue: 5,
    rewardPoints: 80,
  },
  {
    id: "achievement-8",
    title: "Эко-комментатор",
    description: "Оставить 20 комментариев",
    icon: "badge_comment",
    targetValue: 20,
    rewardPoints: 60,
  },
  {
    id: "achievement-9",
    title: "Любимец сообщества",
    description: "Получить 25 лайков на постах",
    icon: "badge_like",
    targetValue: 25,
    rewardPoints: 100,
  },
  {
    id: "achievement-10",
    title: "Стабильный шаг",
    description: "Выполнять активности 7 дней подряд",
    icon: "badge_streak_7",
    targetValue: 7,
    rewardPoints: 70,
  },
  {
    id: "achievement-11",
    title: "Зеленая серия",
    description: "Выполнять активности 30 дней подряд",
    icon: "badge_streak_30",
    targetValue: 30,
    rewardPoints: 200,
  },
  {
    id: "achievement-12",
    title: "Бережливый пользователь",
    description: "Сэкономить 500 литров воды",
    icon: "badge_water",
    targetValue: 500,
    rewardPoints: 100,
  },
  {
    id: "achievement-13",
    title: "Спасатель климата",
    description: "Сократить 100 кг CO2",
    icon: "badge_co2",
    targetValue: 100,
    rewardPoints: 150,
  },
  {
    id: "achievement-14",
    title: "Энерго-герой",
    description: "Сэкономить 100 кВт·ч энергии",
    icon: "badge_energy",
    targetValue: 100,
    rewardPoints: 120,
  },
  {
    id: "achievement-15",
    title: "Переработчик",
    description: "Переработать 50 единиц отходов",
    icon: "badge_recycle",
    targetValue: 50,
    rewardPoints: 90,
  },
];

export const mockPosts: CommunityPostDetail[] = [
  {
    id: "post-1",
    author: "green_step",
    content: "Started walking to university this week instead of taking a taxi.",
    state: "Needs review",
    reportsCount: 3,
    media: [],
    createdAt: "2025-03-14",
  },
  {
    id: "post-2",
    author: "eco_daily",
    content: "Shared a checklist for reducing water use at home.",
    state: "Published",
    reportsCount: 0,
    media: [],
    createdAt: "2025-03-15",
  },
  {
    id: "post-3",
    author: "urban_leaf",
    content: "Posted a photo dump with repeated promotional captions.",
    state: "Needs review",
    reportsCount: 2,
    media: [],
    createdAt: "2025-03-16",
  },
  {
    id: "post-4",
    author: "recycle_hub",
    content: "Community cleanup event recap with location details.",
    state: "Hidden",
    reportsCount: 1,
    media: [],
    createdAt: "2025-03-13",
  },
];
